# ./docker-compose.yml

version: '3.8'

services:
  # This is your existing web application service
  cycleapp:
    build: .
    container_name: cycleapp_container
    restart: unless-stopped
    volumes:
      - ./src:/usr/share/nginx/html
      - ./src/schedule.json:/usr/share/nginx/html/schedule.json

  # This is the new Cloudflare Tunnel service
  cloudflared-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel_container
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - cycleapp

  # This is the new reminder service
  reminder:
    build:
      context: .
      dockerfile: reminder.Dockerfile
    container_name: reminder_container
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./src/schedule.json:/app/src/schedule.json
    command: ["python", "send_reminder.py"]

